apiVersion: v1
kind: Service
metadata:
  name: doctor
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: doctor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor
  template:
    metadata:
      labels:
        app: doctor
    spec:
      containers:
        - name: doctor
          image: serrodcal/doctor:1.0.0-native-distroless
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 300M
              cpu: 300m
            limits:
              memory: 300M
              cpu: 300m