apiVersion: v1
kind: Service
metadata:
  name: health
spec:
  ports:
    - name: https
      port: 8253
      targetPort: 8253
      protocol: TCP
    - name: http
      port: 8290
      targetPort: 8290
      protocol: TCP
    - name: mi-mgnt
      port: 9164
      targetPort: 9164
      protocol: TCP
  selector:
    app: health
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
        - name: health
          image: serrodcal/health:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8253
              protocol: TCP
            - containerPort: 8290
              protocol: TCP
            - containerPort: 9164
              protocol: TCP
          resources:
            requests:
              memory: 300M
              cpu: 300m
            limits:
              memory: 300M
              cpu: 300m
          volumeMounts:
            - name: observability-config
              mountPath: /home/wso2carbon/wso2mi-1.2.0/conf/deployment.toml
              subPath: deployment.toml
      volumes:
        - name: observability-config
          configMap:
            name: wso2-ei-cm
            items:
              - key: deployment.toml
                path: deployment.toml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: wso2-ei-cm
data:
  deployment.toml: |
    [server]
    hostname = "localhost"
    hot_deployment = false

    [user_store]
    type = "read_only_ldap"

    [keystore.tls]
    file_name = "wso2carbon.jks"
    password = "wso2carbon"
    alias = "wso2carbon"
    key_password = "wso2carbon"

    [truststore]
    file_name = "client-truststore.jks"
    password = "wso2carbon"
    alias = "symmetric.key.value"
    algorithm = "AES"

    [mediation]
    flow.statistics.capture_all= true
    stat.tracer.collect_payloads= true
    stat.tracer.collect_mediation_properties= true

    [opentracing]
    enable = true
    logs = true
    manager_host = "jaeger"
    agent_host = "jaeger"