apiVersion: v1
kind: Service
metadata:
  name: hospital
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: hospital
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital
  template:
    metadata:
      labels:
        app: hospital
    spec:
      containers:
        - name: hospital
          image: serrodcal/hospital:1.0.0-native-distroless
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 300M
              cpu: 300m
            limits:
              memory: 300M
              cpu: 300m